chore: fix the github CI error when building Android target
Change the JAVA SDK to JAVA17 on MacOS arm64 chips

This commit is to fix the following error when running action on MacOS target
with Apple sillicon chips.

Error: LinkageError occurred while loading main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli
has been compiled by a more recent version of the Java Runtime (class file
version 61.0), this version of the Java Runtime only recognizes class file
versions up to 55.0

The class com.android.sdklib.tool.sdkmanager.SdkManagerCli was compiled with a
newer version of Java (class file version 61.0, which corresponds to Java 17),
but the Java runtime environment being used only supports class file versions up
to 55.0 (which corresponds to Java 11).